# Example pattern item with all possible options:
# - pattern: "(?P<year>\\d{4})(?P<month>\\d{2})-(?P<doctype>V7RE)-(?P<docnum>\\d+)\\.pdf"
#   destination: "C:\\Archive\\{doctype}\\{year}\\{month}"
#   print: true
#   printer: "HP LaserJet"

default_printer: "ET-3850 Series(Netzwerk)"

patterns:
 - pattern: "V7RE-(?P<year>\\d{4})(?P<month>\\d{2})\\d{2}-\\d+\\.pdf$"
   destination: "C:\\Users\\gpete\\Downloads\\test\\{year}\\{month}"
   print: true